name: Linting

on:
  pull_request:
  workflow_run:
    workflows: [PR check]
    types:
      - completed
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
  prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Open sha file
      #  uses: dawidd6/action-download-artifact@v2
      #  with:
      #    workflow: ${{ github.event.workflow_run.workflow_id }}
      #    name: pull-request-sha
      #- name: Grab pull request sha1
      #  run: |
      #    pr_sha=`cat pr-sha.txt`
      #    echo "PR_SHA=$pr_sha" >> $GITHUB_ENV

      - name: Vale
        uses: errata-ai/vale-action@master
        with:
          styles: |
            https://github.com/errata-ai/Google/releases/latest/download/Google.zip
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
            
          onlyAnnotateModifiedLines: true

          files: docs/data
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          # OVERRIDE_GITHUB_SHA: ${{env.PR_SHA}}
